Mod color
AttorneyOnline/tsuserver3 pull request #121
Opened 2020-09-10 18:27 UTC by stonedDiscord

this was requested by 2 servers because their playerbase typically doesn't read OOC.

Yes i am aware that people can change their colors but this can still be useful, because even if someone does; one of the colors is still reserved

2020-09-10 18:39 UTC, Crystalwarrior commented
Instead of mod colors, wouldn't it be better to use the showname system to prepend a non-spoofable [M] tag? It is much harder to mistake for something occuring in-character this way, and colors are more ambiguous than the mod tag.
KFO-Server employs this system - when you are logged in as mod, your IC messages and OOC messages both have [M].

2020-09-10 18:40 UTC, Crystalwarrior commented
Additional criticism is there's zero feedback for the client why any particular color suddenly didn't work - it can easily be mistaken for a bug due to lack of any communication why a certain color was reset.

2020-09-11 14:47 UTC, oldmud0 requested changes
Doesn't address use of the mod color in inline text.

2021-05-11 20:57 UTC, stonedDiscord commented
inline text color was a mistake

2021-05-11 20:57 UTC, closed without merging