Ban fix
AttorneyOnline/tsuserver3 pull request #47
Opened 2019-01-01 11:28 UTC by perplexedMurfy

The ban reason is now stored with the banned ipid in `banlist.json` where the form for each ban entry is `[ipid, reason]`. This does mean that old banlists need to be updated to this format. I added a (probably kinda jank) check on `load_banlist` to see if we need to update the format, and a method to upgrade old banlists to the new format (all reasons are set to "N/A" when upgrading). 
The ban reason is now sent to clients in the BD packet. But a change needs to happen in the client so the client will show the ban reason.

There was also a ban check in `net_cmd_hi` that I don't believe can get hit. I wasn't quite sure so I decided to update that to send the reason as well.

2019-01-01 11:35 UTC, Parazoid commented
Looks good, not sure about changing the banlist format though.

2019-01-01 18:06 UTC, oldmud0 requested changes
It makes more design sense to migrate the ban list to a dictionary (key-value store) instead of simply converting entries to tuples. This will improve lookup times and give the ban store room for extensibility.

Example:
```json
{
  "1121": { "reason": "Spam" },
  "2445": {}
}
```
You can leave legacy ban entries as empty objects, or add the "N/A" reason as you did.

2019-01-01 22:59 UTC, perplexedMurfy commented
That commit should account the changes that you requested.

2019-01-02 15:37 UTC, oldmud0 approved these changes

2019-01-02 15:38 UTC, merged