Default ban duration on the config file
AttorneyOnline/tsuserver3 pull request #67
Opened 2019-08-17 19:31 UTC by cents02

This time it works.
**Important note:** please update your config files with the new entry!

2019-08-17 20:11 UTC, oldmud0 requested changes

2019-08-17 20:11 UTC, oldmud0 commented on config_sample/config.yaml
> +bandur: 6
There's no need to be ultra-concise in a configuration file - just say `default_ban_duration`.

No units are specified. There is no indication that the number 6 refers to 6 hours.

Use a string instead that accepts the same duration syntax as the `/ban` command (including `perma`).

Suggestion:
```yaml
# If no ban duration is specified, this one will be used.
# This duration follows the same syntax as the /ban command.
# Examples: "6 hours", "6h", "1 day", "1d", "perma"
default_ban_duration: 6h
```

2019-08-17 20:11 UTC, oldmud0 commented on server/commands/admin.py
> +            bandur = client.server.config['bandur']
This will cause an error if the configuration entry is missing in the YAML. You will need to use a try/except to cover this case.

2021-02-23 18:04 UTC, stonedDiscord commented
#154

2021-02-23 18:04 UTC, closed without merging